import React from 'react';

import classes from './About.module.css'

const About = props => {
    return (
        <div className={classes.about}>
            <h1>This is the About Page.</h1>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Dolor sit amet consectetur adipiscing elit ut aliquam. Ipsum suspendisse ultrices gravida dictum fusce. Justo eget magna fermentum iaculis eu non diam phasellus vestibulum. Viverra justo nec ultrices dui. Viverra vitae congue eu consequat ac felis donec et odio. Pretium viverra suspendisse potenti nullam ac tortor vitae. Vestibulum lorem sed risus ultricies tristique nulla aliquet. Orci dapibus ultrices in iaculis nunc sed augue. Nisl pretium fusce id velit ut. Leo vel fringilla est ullamcorper eget nulla facilisi etiam. Non pulvinar neque laoreet suspendisse interdum consectetur libero id faucibus. Diam sit amet nisl suscipit adipiscing bibendum est ultricies integer. Ornare quam viverra orci sagittis eu volutpat odio facilisis. Mi eget mauris pharetra et.

Sed ullamcorper morbi tincidunt ornare massa. Platea dictumst quisque sagittis purus. Mattis rhoncus urna neque viverra justo nec. Nulla malesuada pellentesque elit eget. Ac tortor vitae purus faucibus ornare suspendisse. Curabitur vitae nunc sed velit dignissim sodales ut eu sem. Sagittis eu volutpat odio facilisis mauris sit amet massa. Mattis rhoncus urna neque viverra justo nec ultrices dui sapien. Euismod quis viverra nibh cras pulvinar mattis nunc. Vel elit scelerisque mauris pellentesque. Egestas quis ipsum suspendisse ultrices gravida dictum fusce ut. Commodo nulla facilisi nullam vehicula. Adipiscing elit ut aliquam purus sit amet luctus venenatis. Arcu vitae elementum curabitur vitae. At quis risus sed vulputate odio ut enim blandit.

Facilisis sed odio morbi quis commodo. Ornare aenean euismod elementum nisi quis eleifend quam. Ut faucibus pulvinar elementum integer enim neque volutpat ac. Vulputate dignissim suspendisse in est. Nisi lacus sed viverra tellus. Leo vel fringilla est ullamcorper eget nulla facilisi. Eget duis at tellus at urna. Dolor sit amet consectetur adipiscing elit ut aliquam purus. Mattis rhoncus urna neque viverra justo nec ultrices. Sed elementum tempus egestas sed sed risus pretium. Tempor id eu nisl nunc mi ipsum faucibus vitae aliquet. Magna etiam tempor orci eu lobortis elementum. Cursus eget nunc scelerisque viverra mauris in aliquam. Vitae nunc sed velit dignissim. Id cursus metus aliquam eleifend mi in nulla posuere sollicitudin. Posuere morbi leo urna molestie at elementum eu.

Tortor posuere ac ut consequat semper viverra nam libero justo. A pellentesque sit amet porttitor eget. Pellentesque habitant morbi tristique senectus et netus et. Lorem mollis aliquam ut porttitor leo a. Cras pulvinar mattis nunc sed blandit libero. Odio facilisis mauris sit amet massa vitae tortor. Nulla at volutpat diam ut venenatis tellus in. Duis convallis convallis tellus id interdum velit laoreet id. Tempor orci eu lobortis elementum nibh. Sagittis purus sit amet volutpat consequat mauris nunc. Pellentesque habitant morbi tristique senectus. Amet tellus cras adipiscing enim eu turpis egestas.

Eu augue ut lectus arcu bibendum at varius vel pharetra. Id donec ultrices tincidunt arcu non sodales neque sodales ut. Pretium fusce id velit ut tortor pretium. Vestibulum sed arcu non odio euismod lacinia at quis risus. Platea dictumst vestibulum rhoncus est pellentesque elit ullamcorper dignissim cras. Metus aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices. Massa massa ultricies mi quis hendrerit dolor magna eget. Egestas egestas fringilla phasellus faucibus scelerisque. Sapien nec sagittis aliquam malesuada bibendum arcu. Purus ut faucibus pulvinar elementum integer enim neque. Elementum facilisis leo vel fringilla est ullamcorper eget nulla facilisi. Pulvinar neque laoreet suspendisse interdum. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros. Sed viverra ipsum nunc aliquet bibendum enim facilisis. Tempor orci dapibus ultrices in iaculis nunc sed augue lacus. Id velit ut tortor pretium viverra suspendisse. Id nibh tortor id aliquet lectus proin. Aliquam sem et tortor consequat. Justo laoreet sit amet cursus sit amet dictum sit amet. Cum sociis natoque penatibus et magnis dis parturient montes nascetur.</p>
        </div>
    );
};

export default About;